version: '3'

services:
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    volumes:
      - ./client:/usr/src
    ports:
      - 3020:3000
    container_name: client
    tty: true

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./server:/app
    ports:
      - "3010:3000"
    tty: true
    stdin_open: true
    depends_on:
      - db
volumes:
  postgres_volume: