version: '3'

services:
  tex_to_img:
    build:
      dockerfile: ./docker/tex_to_img/Dockerfile
    container_name: tex_to_img
    ports:
      - "5001:5001"
    tty: true
    volumes:
      - ../src:/root/src
  
  # front:
  #   build:
  #     dockerfile: ./docker/front/Dockerfile
  #   command: pnpm run dev
  #   volumes:
  #     - ./front:/app
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - server
  #   restart: always

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"

  server:
    build:
      dockerfile: ./docker/server/Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./server:/app
    ports:
      - "3010:3000"
    restart: always
    tty: true
    stdin_open: true
    depends_on:
      - db
volumes:
  postgres_volume: